name: MineChess
version: 1.0.0
api: 5.0.0
author: SandhyR
main: SandhyR\MineChess\MineChess
src-namespace-prefix: SandhyR\MineChess

depend:
  - Customies

permissions:
  minechess.command:
    default: true
